# Generated by Django 5.1.7 on 2026-03-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='site',
            new_name='email',
        ),
    ]
